---
  - hosts: database
    become: true
    tasks:
      - name: Install mysql-server
        apt: name=mysql-server state=present update_cache=yes

      - name: Ensure mysql-server started
        service: name=mysql-server state=started enabled=yes