---
- hosts: loadbalancer
  become: true
  tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-httplib2

    - name: Install nginx
      apt: name=nginx state=present update_cache=yes

    - name: Ensure nginx started
      service: name=nginx state=started enabled=yes

    - name: configure nginx load balancer
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644

    - name: deactivate nginx default page
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify: restart nginx
    
    - name: activate nginx site
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted