---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx status
      command: service nginx status
    
    - name: verify nginx is listengin on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 status
      command: service apache2 status

    - name: verify apache2 is listengin on 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify database status
      command: service mysql status

    - name: verify mysql is listengin on 3306
      wait_for: port=3306 timeout=1